Add correct target as per Steve's feedback

diff --git a/git-hooks/post-checkout b/git-hooks/post-checkout
--- a/git-hooks/post-checkout
+++ b/git-hooks/post-checkout
@@ -1,4 +1,4 @@
 #!/bin/bash
 
 echo "rebuilding extension"
-(npm install && npm run build) || echo "fail to rebuild javascript"
+(npm install && npm run build:main) || echo "fail to rebuild javascript"
